import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>State of Ridgeway</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main h-screen w-screen flex items-center justify-center flex-col">
        <img
          className="h-16"
          alt="Logo"
          src="https://cdn.discordapp.com/attachments/884302457923072000/889218554510082118/Group_2.png"
        />
        <span className="text-white text-lg font-semibold mt-2">
          We're currently loading server assets... this should only take a
          minute!
        </span>
        <div>
          <svg
            className="animate-spin text-white mt-8 h-8 w-8"
            viewBox="0 0 512 512"
          >
            <path
              xmlns="http://www.w3.org/2000/svg"
              fill="currentColor"
              d="M288 39.056v16.659c0 10.804 7.281 20.159 17.686 23.066C383.204 100.434 440 171.518 440 256c0 101.689-82.295 184-184 184-101.689 0-184-82.295-184-184 0-84.47 56.786-155.564 134.312-177.219C216.719 75.874 224 66.517 224 55.712V39.064c0-15.709-14.834-27.153-30.046-23.234C86.603 43.482 7.394 141.206 8.003 257.332c.72 137.052 111.477 246.956 248.531 246.667C393.255 503.711 504 392.788 504 256c0-115.633-79.14-212.779-186.211-240.236C302.678 11.889 288 23.456 288 39.056z"
            />
          </svg>
        </div>
      </div>
    </div>
  );
}
